/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.github.pflooky.datagen

import com.github.pflooky.datagen.core.generator.plan.datasource.DataSourceMetadataFactory
import org.apache.log4j.Logger

import java.time.{Duration, LocalDateTime}

object App {

  private val LOGGER = Logger.getLogger(getClass.getName)

  def main(args: Array[String]): Unit = {
    val startTime = LocalDateTime.now()
    new DataSourceMetadataFactory().extractAllDataSourceMetadata()
//    new DataGeneratorProcessor().generateData()
    val endTime = LocalDateTime.now()
    val duration = Duration.between(startTime, endTime)
    LOGGER.info(s"Completed in ${duration.toSeconds}s")
  }
}
